version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - .:/usr/src/app 
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
